# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170324_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
