# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_qtd',
            field=models.IntegerField(null=True),
        ),
    ]
