# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20170324_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_qtd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
